contracts/pool/TridentERC20.sol
- add function to calculate domain separator to help avoid replay attacks by updating chain id
- minor reformatting changes
=> add replay protection to TridentERC20

test/ConcentratedLiquidityPoolTest.ts
Add tests for INVALID_TICK (LOWER), LOWER_EVEN, INVALID_TICK (UPPER), UPPER_ODD
=> Added tests that cover INVALID_TICK (LOWER), LOWER_EVEN, INVALID_TICK (UPPER), UPPER_ODD

contracts/pool/concentrated/ConcentratedLiquidityPosition.sol
add wrapping function to fetch pool pair tokens / nit error msg / remove duplicative imports
=> Conc position optimization

contracts/pool/concentrated/TridentNFT.sol
- add replay protection
- optimize counters with unchecked
- add `permitAll` function
- update comments, style changes
=> optimize TridentNFT for conc

.solhint.json, contracts/interfaces/IConcentratedLiquidityPool.sol, contracts/libraries/concentratedPool/DyDxMath.sol, contracts/libraries/concentratedPool/Ticks.sol, contracts/pool/ConstantProductPool.sol, contracts/pool/concentrated/ConcentratedLiquidityPool.sol, contracts/pool/concentrated/ConcentratedLiquidityPosition.sol, test/ConcentratedLiquidityPoolTest.ts, test/harness/Concentrated.ts, test/harness/Trident.ts
=> Revert "Make concentrated pool deployable"

test/router/RoutingMultiPool.test.ts, test/router/helpers/routerParamsHelper.ts
- Updated tests to include default slippage & min output
- Added test for high slippage
=> Tines: Routing multi pool tests include slippage

contracts/pool/concentrated/ConcentratedLiquidityPool.sol, test/ConcentratedLiquidityPoolTest.ts
Decrease correct amount from reserves upon burning.
round down amounts when burning.
=> Decrease correct amount from reserves upon burning

contracts/pool/concentrated/ConcentratedLiquidityPoolManager.sol, test/ConcentratedLiquidityPoolTest.ts
Also increase incentive expiration buffer
=> Concentrated manager events

contracts/pool/ConstantProductPool.sol
We add this require on the public view function
=> add require on the view function

package.json, test/router/RoutingMultiPool.test.ts, test/router/helpers/index.ts, test/router/helpers/routerParams.ts, yarn.lock
- Updated to use latest version of Tines
=> test: tines bump version

contracts/TridentRouter.sol, contracts/interfaces/IBentoBoxMinimal.sol, contracts/utils/RouterHelper.sol
Allows for batching the first trade in 1 transaction
=> feat - add master contract approval function

.gitignore, contracts/pool/ConstantProductPool.sol, contracts/pool/HybridPool.sol, test/harness/ConstantProduct.ts
=> [WIP] Minor changes to CP

contracts/pool/concentrated/README.md
betwen -> between
untill -> until
=> Fix typo in concentrated/README.md

contracts/abstract/Multicall.sol
- optimize loop incrementor / add header
=> optimizations

contracts/TridentRouter.sol, test/router/TridentRouter.test.ts
🥢style cleanups and custom error
=> router cleanups

contracts/TridentRouter.sol, contracts/libraries/SafeTransferLib.sol
add univ2 safeTransferLib with solmate ETH helper for immediate purposes
=> traditional transfer helper

contracts/deployer/MasterDeployer.sol, test/deployer/MasterDeployer.test.ts
resolves https://github.com/sushiswap/trident/issues/319
=> custom errors in master deployer

contracts/pool/constant-product/ConstantProductPool.sol
=> fixed invalid amount check

contracts/migration/TridentSushiRollCP.sol, test/migration/Migration.test.ts
Can migrate between different cp configurations and cp pools from different factories
=> Cp migrator

contracts/libraries/TridentMath.sol
gas optimization, see https://github.com/Rari-Capital/solmate/pull/212/files
=> more efficient sqrt

.vscode/settings.json, deploy/StablePoolFactory.ts, package.json, test/constant-product/ConstantProductPool.test.ts, test/fixtures/constant-product/index.ts, test/fixtures/constant-product/initializedConstantProductPool.ts, test/fixtures/constant-product/uninitializedConstantProductPool.ts, test/fixtures/index.ts, test/fixtures/stable-pool/index.ts, test/fixtures/stable-pool/initializedStablePool.ts, test/fixtures/stable-pool/vanillaInitializedStablePool.ts, test/stable-pool/StablePool.test.ts, test/stable-pool/StablePoolRouting.test.ts
Should be good to go now, just basic tests for coverage on majority of stable-pool and covered a couple missing ones for constant-product
Just a 1st pass through on getting coverage up, will get some more complex tests in next to try to get the rest of the cases covered in stable pool.
=> Additional StablePool Tests
